### ISSUE TITLE
chrome failure when creating the browser

### ISSUE THREAD

**Issue by akostadinov** [titusfortner/watir_angular#3]
I'm hitting the following issue on chrome:
```
      unknown error: Cannot set property 'pageFinishedRendering' of undefined
        (Session info: chrome=61.0.3163.100)
        (Driver info: chromedriver=2.32.498513 (2c63aa53b2c658de596ed550eb5267ec5967b351),platform=Linux 4.12.13-300.fc26.x86_64 x86_64) (Selenium::WebDriver::Error::UnknownError)
      /home/avalon/.gem/ruby/2.4.0/gems/selenium-webdriver-3.7.0/lib/selenium/webdriver/remote/response.rb:69:in `assert_ok'
      /home/avalon/.gem/ruby/2.4.0/gems/selenium-webdriver-3.7.0/lib/selenium/webdriver/remote/response.rb:32:in `initialize'
      /home/avalon/.gem/ruby/2.4.0/gems/selenium-webdriver-3.7.0/lib/selenium/webdriver/remote/http/common.rb:81:in `new'
      /home/avalon/.gem/ruby/2.4.0/gems/selenium-webdriver-3.7.0/lib/selenium/webdriver/remote/http/common.rb:81:in `create_response'
      /home/avalon/.gem/ruby/2.4.0/gems/selenium-webdriver-3.7.0/lib/selenium/webdriver/remote/http/default.rb:104:in `request'
      /home/avalon/.gem/ruby/2.4.0/gems/selenium-webdriver-3.7.0/lib/selenium/webdriver/remote/http/common.rb:59:in `call'
      /home/avalon/.gem/ruby/2.4.0/gems/selenium-webdriver-3.7.0/lib/selenium/webdriver/remote/bridge.rb:168:in `execute'
      /home/avalon/.gem/ruby/2.4.0/gems/selenium-webdriver-3.7.0/lib/selenium/webdriver/remote/oss/bridge.rb:579:in `execute'
      /home/avalon/.gem/ruby/2.4.0/gems/selenium-webdriver-3.7.0/lib/selenium/webdriver/remote/oss/bridge.rb:267:in `execute_script'
      /home/avalon/.gem/ruby/2.4.0/gems/selenium-webdriver-3.7.0/lib/selenium/webdriver/common/driver.rb:211:in `execute_script'
      /home/avalon/.gem/ruby/2.4.0/bundler/gems/watir_angular-217983f0c583/lib/watir_angular.rb:17:in `wait_for_angular'
      /home/avalon/.gem/ruby/2.4.0/bundler/gems/watir_angular-217983f0c583/lib/watir_angular.rb:11:in `block in initialize'
      /home/avalon/.gem/ruby/2.4.0/bundler/gems/watir-c20be71b68e3/lib/watir/after_hooks.rb:70:in `block in run'
      /home/avalon/.gem/ruby/2.4.0/bundler/gems/watir-c20be71b68e3/lib/watir/after_hooks.rb:101:in `block in each'
      /home/avalon/.gem/ruby/2.4.0/bundler/gems/watir-c20be71b68e3/lib/watir/after_hooks.rb:101:in `each'
      /home/avalon/.gem/ruby/2.4.0/bundler/gems/watir-c20be71b68e3/lib/watir/after_hooks.rb:101:in `each'
      /home/avalon/.gem/ruby/2.4.0/bundler/gems/watir-c20be71b68e3/lib/watir/after_hooks.rb:70:in `run'
      /home/avalon/.gem/ruby/2.4.0/bundler/gems/watir-c20be71b68e3/lib/watir/browser.rb:83:in `goto'
      /home/avalon/ws/repos/cucushift/lib/webauto/web4cucumber.rb:429:in `goto_url'
      /home/avalon/ws/repos/cucushift/lib/webauto/web4cucumber.rb:188:in `block in run_action'
      /home/avalon/ws/repos/cucushift/lib/webauto/web4cucumber.rb:184:in `each'
      /home/avalon/ws/repos/cucushift/lib/webauto/web4cucumber.rb:184:in `run_action'
      /home/avalon/ws/repos/cucushift/lib/webauto/webconsole_executor.rb:108:in `login'
      /home/avalon/ws/repos/cucushift/lib/webauto/webconsole_executor.rb:137:in `run_action'
      /home/avalon/ws/repos/cucushift/lib/openshift/user.rb:110:in `webconsole_exec'
      /home/avalon/ws/repos/cucushift/features/step_definitions/web.rb:6:in `block in <top (required)>'
      /home/avalon/.gem/ruby/2.4.0/gems/cucumber-2.4.0/lib/cucumber/core_ext/instance_exec.rb:25:in `instance_exec'
      /home/avalon/.gem/ruby/2.4.0/gems/cucumber-2.4.0/lib/cucumber/core_ext/instance_exec.rb:25:in `block in cucumber_instance_exec'
      /home/avalon/.gem/ruby/2.4.0/gems/cucumber-2.4.0/lib/cucumber/core_ext/instance_exec.rb:42:in `cucumber_run_with_backtrace_filtering'
      /home/avalon/.gem/ruby/2.4.0/gems/cucumber-2.4.0/lib/cucumber/core_ext/instance_exec.rb:13:in `cucumber_instance_exec'
      /home/avalon/.gem/ruby/2.4.0/gems/cucumber-2.4.0/lib/cucumber/rb_support/rb_step_definition.rb:102:in `invoke'
      /home/avalon/.gem/ruby/2.4.0/gems/cucumber-2.4.0/lib/cucumber/step_match.rb:27:in `invoke'
      /home/avalon/.gem/ruby/2.4.0/gems/cucumber-2.4.0/lib/cucumber/step_match.rb:20:in `block in activate'
      /home/avalon/.gem/ruby/2.4.0/gems/cucumber-core-1.5.0/lib/cucumber/core/test/action.rb:23:in `execute'
      /home/avalon/.gem/ruby/2.4.0/gems/cucumber-core-1.5.0/lib/cucumber/core/test/step.rb:31:in `execute'
      /home/avalon/.gem/ruby/2.4.0/gems/cucumber-core-1.5.0/lib/cucumber/core/test/runner.rb:104:in `execute'
      /home/avalon/.gem/ruby/2.4.0/gems/cucumber-core-1.5.0/lib/cucumber/core/test/runner.rb:51:in `execute'
      /home/avalon/.gem/ruby/2.4.0/gems/cucumber-core-1.5.0/lib/cucumber/core/test/runner.rb:26:in `test_step'
      /home/avalon/.gem/ruby/2.4.0/gems/cucumber-core-1.5.0/lib/cucumber/core/test/step.rb:16:in `describe_to'
      /home/avalon/.gem/ruby/2.4.0/gems/cucumber-core-1.5.0/lib/cucumber/core/test/case.rb:26:in `block (3 levels) in describe_to'
      /home/avalon/.gem/ruby/2.4.0/gems/cucumber-core-1.5.0/lib/cucumber/core/test/case.rb:25:in `each'
      /home/avalon/.gem/ruby/2.4.0/gems/cucumber-core-1.5.0/lib/cucumber/core/test/case.rb:25:in `block (2 levels) in describe_to'
      /home/avalon/.gem/ruby/2.4.0/gems/cucumber-2.4.0/lib/cucumber/filters/prepare_world.rb:22:in `block in test_case'
      /home/avalon/.gem/ruby/2.4.0/gems/cucumber-core-1.5.0/lib/cucumber/core/test/around_hook.rb:16:in `execute'
      /home/avalon/.gem/ruby/2.4.0/gems/cucumber-core-1.5.0/lib/cucumber/core/test/runner.rb:104:in `execute'
      /home/avalon/.gem/ruby/2.4.0/gems/cucumber-core-1.5.0/lib/cucumber/core/test/runner.rb:51:in `execute'
      /home/avalon/.gem/ruby/2.4.0/gems/cucumber-core-1.5.0/lib/cucumber/core/test/runner.rb:33:in `around_hook'
      /home/avalon/.gem/ruby/2.4.0/gems/cucumber-core-1.5.0/lib/cucumber/core/test/around_hook.rb:11:in `describe_to'
      /home/avalon/.gem/ruby/2.4.0/gems/cucumber-core-1.5.0/lib/cucumber/core/test/case.rb:106:in `block (2 levels) in compose_around_hooks'
      /home/avalon/.gem/ruby/2.4.0/gems/cucumber-core-1.5.0/lib/cucumber/core/test/case.rb:107:in `compose_around_hooks'
      /home/avalon/.gem/ruby/2.4.0/gems/cucumber-core-1.5.0/lib/cucumber/core/test/case.rb:24:in `block in describe_to'
      /home/avalon/.gem/ruby/2.4.0/gems/cucumber-core-1.5.0/lib/cucumber/core/test/runner.rb:18:in `test_case'
      /home/avalon/.gem/ruby/2.4.0/gems/cucumber-core-1.5.0/lib/cucumber/core/test/case.rb:23:in `describe_to'
      /home/avalon/.gem/ruby/2.4.0/gems/cucumber-2.4.0/lib/cucumber/filters/prepare_world.rb:11:in `test_case'
      /home/avalon/.gem/ruby/2.4.0/gems/cucumber-core-1.5.0/lib/cucumber/core/test/case.rb:23:in `describe_to'
      /home/avalon/.gem/ruby/2.4.0/gems/cucumber-2.4.0/lib/cucumber/filters/apply_around_hooks.rb:8:in `test_case'
      /home/avalon/.gem/ruby/2.4.0/gems/cucumber-core-1.5.0/lib/cucumber/core/test/case.rb:23:in `describe_to'
      /home/avalon/.gem/ruby/2.4.0/gems/cucumber-2.4.0/lib/cucumber/filters/apply_after_hooks.rb:5:in `test_case'
      /home/avalon/.gem/ruby/2.4.0/gems/cucumber-core-1.5.0/lib/cucumber/core/test/case.rb:23:in `describe_to'
      /home/avalon/.gem/ruby/2.4.0/gems/cucumber-2.4.0/lib/cucumber/filters/apply_before_hooks.rb:5:in `test_case'
      /home/avalon/.gem/ruby/2.4.0/gems/cucumber-core-1.5.0/lib/cucumber/core/test/case.rb:23:in `describe_to'
      /home/avalon/.gem/ruby/2.4.0/gems/cucumber-2.4.0/lib/cucumber/filters/apply_after_step_hooks.rb:8:in `test_case'
      /home/avalon/.gem/ruby/2.4.0/gems/cucumber-core-1.5.0/lib/cucumber/core/test/case.rb:23:in `describe_to'
      /home/avalon/.gem/ruby/2.4.0/gems/cucumber-2.4.0/lib/cucumber/filters/activate_steps.rb:11:in `test_case'
      /home/avalon/.gem/ruby/2.4.0/gems/cucumber-core-1.5.0/lib/cucumber/core/test/case.rb:23:in `describe_to'
      /home/avalon/.gem/ruby/2.4.0/gems/cucumber-2.4.0/lib/cucumber/filters/quit.rb:11:in `test_case'
      /home/avalon/.gem/ruby/2.4.0/gems/cucumber-core-1.5.0/lib/cucumber/core/test/case.rb:23:in `describe_to'
      /home/avalon/.gem/ruby/2.4.0/gems/cucumber-core-1.5.0/lib/cucumber/core/test/filters/locations_filter.rb:17:in `block in done'
      /home/avalon/.gem/ruby/2.4.0/gems/cucumber-core-1.5.0/lib/cucumber/core/test/filters/locations_filter.rb:16:in `each'
      /home/avalon/.gem/ruby/2.4.0/gems/cucumber-core-1.5.0/lib/cucumber/core/test/filters/locations_filter.rb:16:in `done'
      /home/avalon/.gem/ruby/2.4.0/gems/cucumber-core-1.5.0/lib/cucumber/core/filter.rb:61:in `done'
      /home/avalon/.gem/ruby/2.4.0/gems/cucumber-core-1.5.0/lib/cucumber/core/test/filters/tag_filter.rb:18:in `done'
      /home/avalon/.gem/ruby/2.4.0/gems/cucumber-core-1.5.0/lib/cucumber/core/compiler.rb:23:in `done'
      /home/avalon/.gem/ruby/2.4.0/gems/cucumber-core-1.5.0/lib/cucumber/core/gherkin/parser.rb:35:in `done'
      /home/avalon/.gem/ruby/2.4.0/gems/cucumber-core-1.5.0/lib/cucumber/core.rb:29:in `parse'
      /home/avalon/.gem/ruby/2.4.0/gems/cucumber-core-1.5.0/lib/cucumber/core.rb:18:in `compile'
      /home/avalon/.gem/ruby/2.4.0/gems/cucumber-2.4.0/lib/cucumber/runtime.rb:67:in `run!'
      /home/avalon/.gem/ruby/2.4.0/gems/cucumber-2.4.0/lib/cucumber/cli/main.rb:32:in `execute!'
      /home/avalon/.gem/ruby/2.4.0/gems/cucumber-2.4.0/bin/cucumber:8:in `<top (required)>'
      /home/avalon/bin/cucumber:23:in `load'
      /home/avalon/bin/cucumber:23:in `<top (required)>'
      /home/avalon/.gem/ruby/2.4.0/gems/bundler-1.15.3/lib/bundler/cli/exec.rb:74:in `load'
      /home/avalon/.gem/ruby/2.4.0/gems/bundler-1.15.3/lib/bundler/cli/exec.rb:74:in `kernel_load'
      /home/avalon/.gem/ruby/2.4.0/gems/bundler-1.15.3/lib/bundler/cli/exec.rb:27:in `run'
      /home/avalon/.gem/ruby/2.4.0/gems/bundler-1.15.3/lib/bundler/cli.rb:365:in `exec'
      /home/avalon/.gem/ruby/2.4.0/gems/bundler-1.15.3/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
      /home/avalon/.gem/ruby/2.4.0/gems/bundler-1.15.3/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
      /home/avalon/.gem/ruby/2.4.0/gems/bundler-1.15.3/lib/bundler/vendor/thor/lib/thor.rb:369:in `dispatch'
      /home/avalon/.gem/ruby/2.4.0/gems/bundler-1.15.3/lib/bundler/cli.rb:22:in `dispatch'
      /home/avalon/.gem/ruby/2.4.0/gems/bundler-1.15.3/lib/bundler/vendor/thor/lib/thor/base.rb:444:in `start'
      /home/avalon/.gem/ruby/2.4.0/gems/bundler-1.15.3/lib/bundler/cli.rb:13:in `start'
      /home/avalon/.gem/ruby/2.4.0/gems/bundler-1.15.3/exe/bundle:30:in `block in <top (required)>'
      /home/avalon/.gem/ruby/2.4.0/gems/bundler-1.15.3/lib/bundler/friendly_errors.rb:121:in `with_friendly_errors'
      /home/avalon/.gem/ruby/2.4.0/gems/bundler-1.15.3/exe/bundle:22:in `<top (required)>'
      /usr/bin/bundle:22:in `load'
      /usr/bin/bundle:22:in `<main>'
      features/web/build.feature:563:in `When I perform the :check_build_strategy web console action with:'
```

**Comment by titusfortner** [comment]
@akostadinov what is the full error message of " of undefined"? do you know what the cause is? Can you make a PR?

**Comment by akostadinov** [comment]
@titusfortner , the pasted error is the full error I see locally. I think some js var is undefined according to chrome but I have not investigated and tbh I'm not very experienced with js. I hoped you will have a better idea what issue can be :)
I'll look at it when I have time in any case, just don't know when I'll have time for it and how successful I'd be on it.

**Comment by titusfortner** [comment]
I have no idea. I'm doing an overhaul of this gem to be released after Watir 6.10. We've updated some code there, and honestly, what I have here is both overly complicated and doesn't do everything it should.

**Comment by titusfortner** [comment]
Let me know if this still happens with 0.3.0

**Comment by titusfortner** [comment]
@akostadinov So I completely re-implemented the script in 0.4.0.
We were using whatever code `westlakem` provided in his Watir PR, but I couldn't find any documentation of the methods he used. I instead went to the protractor project and found what they are currently using. Please let me know if that has any new problems, or if it fixes this issue.

Thanks.
